version: '3'
services:
  db:
    container_name: mysql
    image: mysql:5.6
    volumes:
      - "~/tmp/mysql-data:/var/lib/mysql"
#   restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root

  webservice:
    container_name: mutillidae 
    depends_on:
      - db
    image: pentestlab/mutillidae:1.0
    links:
      - db
    ports:
      - "8000:80"
#    restart: always
