version: 2
jobs:
  build:
    docker:
      - image: webdevops/php-apache:alpine-php7
    steps:
      - checkout
      - setup_remote_docker:   # (2)
          d: true # (3)

      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.12.1-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      # build and push Docker image
      - run: |
          TAG=1.1.$CIRCLE_BUILD_NUM
          docker build -t pentestlab/mutillidae:$TAG .
          docker build -t pentestlab/mutillidae:latest .
          docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
          docker push pentestlab/mutillidae:$TAG
          docker push pentestlab/mutillidae:latest
